getwd()
setwd("/Users/aedan/Documents/Econometrics/Paper")
Players = read.csv("player_data copy.csv")
fix(Players)
Playersreg1=lm(wage ~ height+weight+wins+goals+losses+appearances+assists+age, data=Players)
summary(Playersreg1)
Playersreg2=lm(wage ~ height+weight+wins+goals+losses+appearances+assists+age+def+mid+att, data=Players)
summary(Playersreg2)
Playersreg3=lm(logwage ~ height+weight+wins+goals+losses+appearances+appsq+assists+age, data=Players)
summary(Playersreg3)
Playersreg4=lm(logwage ~ height+weight+wins+goals+losses+appearances+appsq+assists+age+def+mid+att, data=Players)
summary(Playersreg4)
summary(Players)
hist(Players$logwage)
plot(Players$logwage,Players$appsq)
abline(lm(Players$logwage ~ Players$appsq))
print(Playersreg1)

